version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/services/app/Dockerfile
    volumes:
      - app_sources:/app
      - app_cache:/app/var/cache
  web:
    build:
      context: ..
      dockerfile: ./docker/services/web/Dockerfile
    depends_on:
      - app
    volumes:
      - app_sources:/app

volumes:
  app_sources:
  app_cache:
