version: "3"

services:
  app:
    volumes:
      - symfony_core_app-sync:/app
  web:
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - symfony_core_app-sync:/app
  node:
    volumes:
      - symfony_core_app-sync:/app

volumes:
  symfony_core_app-sync:
    external: true
  symfony_core_web-sync:
    external: true
