version: "3"

services:
  app:
    volumes:
      - ..:/app
  web:
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ../public:/app/public
  node:
    volumes:
      - ..:/app
  phpmyadmin:
    build:
      context: ..
      dockerfile: ./docker/services/phpmyadmin/Dockerfile
    depends_on:
      - database
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8082:80
  maildev:
    build:
      context: ..
      dockerfile: ./docker/services/maildev/Dockerfile
    ports:
      - 8083:80
